sudo: required
services:
    - docker
    
before_install:
    - docker build -t ddinesherode/docker-react -f Dockerfile.dev .

scripts:
    - docker run ddinesherode/docker-react npm run test -- --coverage